site_name: theroyakash algorithms
site_url: https://algorithms.theroyakash.com

nav:
  - Introduction: index.md
  - Freebies: freebies.md
  - Blind 75 Problems: ./blind75.md
  - Arrays: 
    - Intro to Arrays: ./arrays/arrays.md
    - Array Problems: ./arrays/array-problems.md
    - Sliding window problems: ./arrays/sliding-window.md
  - Stacks:
    - Stacks Usage: ./stacks/usage.md
    - Stack Problems: ./stacks/problems.md
  - Linked List: 
    - Linked List STL Usage: ./LinkedLists/stl-usage.md
    - Linked List problems: ./LinkedLists/problems.md
  - Binary Search: ./bss.md

theme:
  name: material
  logo: images/logo.png
  features:
    - navigation.expand
    - navigation.top
  palette:
    primary: white
    accent: red
  font:
    code: Ubuntu Mono
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

plugins:
  - search
  - tags

markdown_extensions:
  - meta
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true 
  - attr_list
  - md_in_html
  
extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


extra:
  generator: false
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/theroyakash
    - icon: fontawesome/brands/github
      link: https://github.com/theroyakash
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/theroyakash

copyright: Copyright &copy; 2022 theroyakash